# Generated by Django 2.2.1 on 2020-01-16 13:59

import API.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('leadText', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to=API.models.Article.uploadLocation)),
                ('isPersian', models.BooleanField()),
                ('isBanner', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicPersianName', models.CharField(max_length=200)),
                ('publicName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BazarToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.TextField(max_length=255)),
                ('refreshToken', models.CharField(max_length=255)),
                ('tokenType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('persianName', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to=API.models.Category.uploadLocation)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Author')),
                ('bookmarkedArticles', models.ManyToManyField(blank=True, db_index=True, related_name='bookmarkers', to='API.Article')),
                ('favoriteCategories', models.ManyToManyField(db_index=True, to='API.Category')),
                ('purchasedArticles', models.ManyToManyField(blank=True, db_index=True, related_name='purchasers', to='API.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monencoWebsite', models.CharField(max_length=200)),
                ('monencoWebsiteTitle', models.CharField(max_length=200)),
                ('persianMonencoWebsiteTitle', models.CharField(max_length=200)),
                ('minCategorySelectCount', models.IntegerField()),
                ('shareFooter', models.TextField(blank=True, default=None, null=True)),
                ('persianShareFooter', models.TextField(blank=True, default=None, null=True)),
                ('aboutUs', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('persianAboutUs', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('cafeBazarCode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('persianName', models.CharField(max_length=200)),
                ('relatedTags', models.ManyToManyField(blank=True, db_index=True, to='API.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBankID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityID', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(2, 'Image Part'), (1, 'Text Part')])),
                ('order', models.FloatField()),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=API.models.ArticlePart.uploadLocation)),
                ('content', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='articles', related_query_name='article', to='API.Tag'),
        ),
    ]
