# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isBanner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='articles', related_query_name='article', to='API.Tag'),
        ),
        migrations.AlterField(
            model_name='articlepart',
            name='type',
            field=models.IntegerField(choices=[(2, 'Image Part'), (1, 'Text Part')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='relatedTags',
            field=models.ManyToManyField(blank=True, db_index=True, to='API.Tag'),
        ),
    ]
