# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190212_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monencoWebsite', models.CharField(max_length=200)),
                ('monencoWebsiteTitle', models.CharField(max_length=200)),
                ('persianMonencoWebsiteTitle', models.CharField(max_length=200)),
                ('minCategorySelectCount', models.IntegerField()),
            ],
        ),
    ]
