# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='persianShareFooter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configs',
            name='shareFooter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
