# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190212_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='purchasedArticles',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='purchasers', to='API.Article'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bookmarkedArticles',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='bookmarkers', to='API.Article'),
        ),
    ]
