# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-17 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20190217_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBankID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityID', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Client')),
            ],
        ),
    ]
