# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-11 18:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20190311_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='configs',
            name='aboutUs',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configs',
            name='persianAboutUs',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
