# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20190311_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.TextField(max_length=255)),
                ('refreshToken', models.CharField(max_length=255)),
                ('tokenType', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cafeBazarPaymentId',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
